[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir -r requirements.txt && pip install --upgrade pip"

[deploy]
startCommand = "gunicorn app:app --workers 1 --threads 1 --timeout 120 --max-requests 1 --max-requests-jitter 1 --bind 0.0.0.0:8080 --log-level debug"
healthcheckPath = "/health"
healthcheckTimeout = 600

[env]
PYTHONUNBUFFERED = "1"
TRANSFORMERS_CACHE = "/tmp/transformers_cache"
HF_HOME = "/tmp/hf_home"
FLASK_ENV = "production"
FLASK_APP = "app.py"
PORT = "8080"
PYTORCH_CUDA_ALLOC_CONF = "max_split_size_mb:128"
TF_CPP_MIN_LOG_LEVEL = "2" 