services:
  - type: web
    name: accent-detection
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
